### ISSUE TITLE
Content above supertabs doesn´t transition when navigating

### ISSUE THREAD

**Issue by karlvd** [zyra/ionic-super-tabs#29]
Again thanks for the awesome work you have done!

I notice that content above super-tabs doesn´t transition when navigating to page containing super-tabs and content above the tabs.

To reproduce:
- Add a div above supertabs
- Navigate to the page from the root Nav controller
![supertabs](https://cloud.githubusercontent.com/assets/3678047/25291788/c15c0a4a-26d3-11e7-83aa-993cbfe385e9.gif)

Edit: there is a `<super-tabs>` tag under the purple box, just couldn´t get it to show. The content in the super tabs gets transitioned correctly. If I remove the `<super-tabs>` under the purple box, the box gets transitioned.

**Comment by karlvd** [comment]
A possible solution/workaround is to use Ionic Native Transitions
[Ionic Native Transitions](https://ionicframework.com/docs/native/native-page-transitions/)

Navigate to pages 
`this.nativePageTransitions.slide({direction: 'left'});`
`this.nav.push(page, params,{animate: false});`

Import the navBar in your class
`@ViewChild(Navbar) navBar: Navbar;`

Override the back button click
```
ionViewDidLoad() {
    this.navBar.backButtonClick = (ev: UIEvent) => {
      this.nativePageTransitions.slide({direction: 'right'});
      this.navCtrl.pop({animate: false});
    };
  }

```

**Comment by ihadeed** [comment]
Thanks for reporting this @karlvd 

I experienced this issue before with one of my apps and I thought it was an issue with the framework. Thanks for taking the time to debug it. I will look into it and fix it.

It seems to happen only with the iOS transition btw.

![super-tabs-issue29-ios](https://cloud.githubusercontent.com/assets/13794420/25338857/ab696abe-28ce-11e7-9ba7-991d051881fe.gif)

![super-tabs-issue29-md](https://cloud.githubusercontent.com/assets/13794420/25338858/acb29c38-28ce-11e7-8a1e-314f04b311d6.gif)

**Comment by ihadeed** [comment]
Quick update, this is a bug with the framework and not with this Super Tabs module. I will try to figure out what the issue is and submit a PR to the framework's repo.

**Comment by timmyrosen** [comment]
Any update on this? I'm also experiencing this issue and can't publish until it is solved

**Comment by ihadeed** [comment]
@timmyrosen I didn't get a chance to look into this yet. I will post an update here once I figure out what's causing it.

**Comment by icharge** [comment]
Me too. I'm trying latest version.

**Comment by eltntawy** [comment]
any update about this...!?

**Comment by ihadeed** [comment]
This was fixed already. I guess newer versions of Ionic reintroduced the problem. I will check this soon.

**Comment by delian7** [comment]
hey @ihadeed love the plugin however I can confirm that this bug is still appearing as of the latest (4.2.2 version).

![animation](https://user-images.githubusercontent.com/4530694/35567803-14e8bb3a-05a5-11e8-9840-a13586559cf5.gif)

**Comment by ihadeed** [comment]
@delian7 what version of `ionic-angular` ?

**Comment by delian7** [comment]
@ihadeed I'm using version 3.9.2.

**Comment by delian7** [comment]
@ihadeed just for planning purposes, any idea of how long this'll take?
