### ISSUE TITLE
Was the swiping bug on load fixed ? 

### ISSUE THREAD

**Issue by aditbharadwaj** [zyra/ionic-super-tabs#400]
https://github.com/zyra/ionic-super-tabs/issues/366#issuecomment-540499783
A question was this fix included in the version 6.1.2 ?  or do we need to use the set-timeout fix as mentioned here :- 
https://github.com/zyra/ionic-super-tabs/issues/366#issuecomment-527094932

thanks :)

**Comment by ihadeed** [comment]
I found multiple issues in the initialization process and fixed them. 

I tested the example project in dev and prod modes, on Chrome, Android, and iOS.

That issue should be fixed. If you experience it again let me know and I'll look into it.

**Comment by bhavik103** [comment]
I had the same issue. I had putted tabs in Home page. And when i run on android device i am not able to swipe the tabs. Sometimes it works fine and sometimes it don't swipe and change tye content of tabs. Anyone have solution for this? It's urgent please.

**Comment by aditbharadwaj** [comment]
> I had the same issue. I had putted tabs in Home page. And when i run on android device i am not able to swipe the tabs. Sometimes it works fine and sometimes it don't swipe and change the content of tabs. Anyone have solution for this? It's urgent please.

use this solution for the time being mentioned here #366 (comment) 
@ihadeed is watching this thread he will , that this issue still persist for some.

**Comment by ihadeed** [comment]
Can you try `6.1.3-alpha.1` ?

**Comment by aditbharadwaj** [comment]
i updated to the latest version and now the tabs are busted for me they are not even changing tabs on clicks.

**Comment by ihadeed** [comment]
@aditbharadwaj thanks for the feedback

Can you share the HTML you're using as well as Ionic/Angular versions (or `ionic info` output)?

I do all my testing on the [example app](https://github.com/zyra/ionic-super-tabs-example) which implements 3 different implementations:
- non-scrollable toolbar
- scrollable toolbar
- no-toolbar

Having more common use cases would help so I can add them there and test them during development.

**Comment by aditbharadwaj** [comment]
sure i will share the data below 
``` my ionic info ```
``` Ionic:

   Ionic CLI                     : 5.2.7 (C:\Users\Adit\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.9.0
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.8.1
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (C:\Users\Adit\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.3 (C:\Program Files\nodejs\node.exe)
   npm               : 6.11.3
   OS                : Windows 10```

```my HTML ```
``` <ion-content >
  <super-tabs class="hydrated" >
    <super-tabs-toolbar slot="bottom" style="height: 61px;"  >
      <super-tab-button>
        <img src="../../assets/imgs/ic_booked_act.png" style="width: 17px; padding-top: 11px;">
       <!--  <ion-icon name="home"></ion-icon> -->
        <ion-label style="padding-top: 4px;">{{'app_title' | translate}}</ion-label>
      </super-tab-button>
      <super-tab-button>
          <img src="../../assets/imgs/loc.png" style="width: 19px; padding-top: 5px;">
        <!-- <ion-icon name="pin"></ion-icon> -->
        <ion-label>{{'Nearby Homes' | translate}}</ion-label>
      </super-tab-button>
      <super-tab-button style="padding-right: 23px;padding-left: 23px;">
          <img src="../../assets/imgs/ic_favorite_act.png" style="width: 19px; padding-top: 11px;">
        <!-- <ion-icon name="md-star"></ion-icon> -->
        <ion-label>{{'recommended' | translate}}</ion-label>
      </super-tab-button>
      <super-tab-button>
          <img src="../../assets/imgs/add.png" style="width: 21px; padding-top: 11px;">
        <!-- <ion-icon name="notifications-outline"></ion-icon> -->
        <ion-label>{{'Saved' | translate}}</ion-label>
      </super-tab-button>
      <super-tab-button>
          <img src="../../assets/imgs/ic_account_act.png" style="width: 22px; padding-top: 11px;">
        <!-- <ion-icon name="contact"></ion-icon> -->
        <ion-label>{{'account' | translate}}</ion-label>
      </super-tab-button>
    </super-tabs-toolbar>
    <super-tabs-container swipeEnabled="false">
      <super-tab >
          <ion-nav [root]="tab1"></ion-nav>
          </super-tab>
      <super-tab>
        <ion-nav [root]="tab2"></ion-nav>
      </super-tab>
      <super-tab>
        <ion-nav [root]="tab3"></ion-nav>
      </super-tab>
      <super-tab>
        <ion-nav [root]="tab4"></ion-nav>
      </super-tab>
      <super-tab>
        <ion-nav [root]="tab5"></ion-nav>
      </super-tab>
      
    </super-tabs-container>
  </super-tabs>
</ion-content>```

**Comment by VaultDeveloper** [comment]
Hello.

I am having the same issue.
I tested a blank project with super-tabs in multiples devices/emulators.
With recent smartphones there is no problems. But with older ones : API 19, Android 4.4, I keep getting errors in the console.

![image](https://user-images.githubusercontent.com/1583606/71663246-b2e3d580-2d54-11ea-8e9f-1f943b373331.png)

I try on different Android emulators and got the same problem, on old API versions.

No errors on Mac devices/emulators.

I will use super-tabs in my company, but I hope this issue will be fixed soon. :)

**Comment by ihadeed** [comment]
@VaultDeveloper that should be fixed in `6.2.1`

This and some other issues are caused by devices that are slow or under heavy load. Some stencil life cycle events fire before the DOM is ready.
